[platformio]
src_dir = .

[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#aa70b80
board = rpipico2
framework = arduino
board_build.core = earlephilhower
lib_extra_dirs = ../../..
build_src_filter = +<*.ino> +<*.cpp>
